config/routes.rb
Rails.application.routes.draw do
  root             'indexes#home'

  get 'treasuredatatags' => 'treasuredatatags#home'
#  get 'treasuredatatags/view'
  post 'treasuredatatagsview' => 'treasuredatatags#view'
#  get 'treasuredatatags/downloadcsv/download'=> 'treasuredatatags#downloadcsv'

  get 'placementtags' => 'placementtags#home'
#  get 'placementtags/view'
  post 'placementtagsview' => 'placementtags#view'
  get 'placementtags/downloadcsv/download'=> 'placementtags#downloadcsv'

  get 'url_checker/index'
  post 'url_checker/index'

  get 'image_test/index'
  post 'image_test/index'

end

app/controllers/placementtags_controller.rb
class PlacementtagsController < ApplicationController
  def home
  end

  def view
  end

  def downloadcsv
    file_name="sample.csv"
    filepath = Rails.root.join('public',file_name)
    stat = File::stat(filepath)
    send_file(filepath, :filename => file_name, :length => stat.size)
  end

end

app/helpers/placementtags_helper.rb
module PlacementtagsHelper
end

app/views/placementtags/home.html.erb
<% provide(:title, "Placementtag Index") %>

<div class="page-header">
	<h1>Sizmek Placement Tag 作成</h1>
</div>

<%= form_tag placementtagsview_path, multipart: true do %>
  <%= file_field_tag :file ,class: "btn btn-default"%>
  <%= submit_tag "インポート", class: "btn btn-primary"  %>
<% end %>

<%= link_to "サンプルCSVファイル",{:action => "downloadcsv"} %>

<div class="list-group">
	<a class="list-group-item" href="#">
		<h4 class="list-group-item-heading">説明：</h4>
		<p class="list-group-item-text">sizmekのプレイスメントタグをプレビューするツールです。</p>
		<p class="list-group-item-text">確認したいcsvファイルを選択してインポートしてください。</p>
		<p class="list-group-item-text">ファイルの1行目はヘッダ行、2行目以降をデータ行としてください。</p>
		<p class="list-group-item-text">ac列にプレイスメントタグが格納されているものとみなし展開します。</p>
		<p class="list-group-item-text">表示の際に1タグにつき1imp発生します。</p>
	</a>
</div>

app/views/placementtags/view.html.erb
<% provide(:title, "Placementtag View") %>

<div class="page-header">
	<h1>Sizmek Placement Tag 作成結果</h1>
</div>

<% headers,lines = csv_split(params[:file]) %>

<table class="table table-bordered table-striped" id="table_id">
  <thead>
    <tr>
      <% headers.each do |header| %>
      <th><%= header %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% lines.each do |line| %>
    <tr>
      <%
        count = 0
        placementid = ""
      %>
      <% line.each do |sel| %>
        <% if count == 0 %>
          <% placementid = sel %>
        <% end %>
        <% if count == 28 %>
          <td><p class="label label-default">タグ</p>
              <p><%= sel %></p>
              <p class="label label-default">表示</p>
              <p id="<%= placementid %>"><%= sel.html_safe %></p>
          </td>
        <% else %>
          <td><%= sel %></td>
        <% end %>
        <% count = count + 1 %>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>