config/routes.rb
Rails.application.routes.draw do
  root             'indexes#home'

  get 'treasuredatatags' => 'treasuredatatags#home'
#  get 'treasuredatatags/view'
  post 'treasuredatatagsview' => 'treasuredatatags#view'
#  get 'treasuredatatags/downloadcsv/download'=> 'treasuredatatags#downloadcsv'

  get 'placementtags' => 'placementtags#home'
#  get 'placementtags/view'
  post 'placementtagsview' => 'placementtags#view'
  get 'placementtags/downloadcsv/download'=> 'placementtags#downloadcsv'

  get 'url_checker/index'
  post 'url_checker/index'

  get 'image_test/index'
  post 'image_test/index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    TradingDesk Check Tools
  </small>
  <nav>
    <ul>
      <li><%= link_to "Index", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarIndex">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "TradingDesk Check Tools", root_path, {id: "logo", class: "navbar-brand" } %>
		</div>
		
		<div class="collapse navbar-collapse navbar-right" id="navbarIndex">
			<ul class="nav navbar-nav">
				<li class="text-right"><%= link_to "UrlChecker",   url_checker_index_path %></li>
				<li class="text-right"><%= link_to "ImageTest",   image_test_index_path %></li>
				<li class="text-right"><%= link_to "Placementtag",   placementtags_path %></li>
				<li class="text-right"><%= link_to "Treasuredatatag",   treasuredatatags_path %></li>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

<script>
$(document).ready(function(){
  $('#table_id').dataTable({
  });
});
</script>

  </head>
  <body>

    <%= render 'layouts/header' %>
    <div class="container">

    <!-- start ドメインが 13.78.48.83 じゃなかったらアラートを表示 -->
    <script language="JavaScript"><!--
    if(document.domain != "13.78.48.83"){
    	console.log("ドメイン名："+document.domain);
    	$('#linkmsg').append('	<a class="list-group-item list-group-item-danger" href="http://13.78.48.83/preview-tools/">このページはテストページです。ここをクリックしてすぐに移動してください。</a>');
    }
    // --></script>
    <div id="linkmsg" class="list-group">
    </div>
    <!-- end ドメインが 13.78.48.83 じゃなかったらアラートを表示 -->

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>